### ISSUE TITLE
Migrating from rxjava to rxjava2 library and support for autoMap

### ISSUE THREAD

**Issue by shubhamarora97** [davidmoten/rxjava2-jdbc#120]
Hi David,

Earlier, in my project, I was using autoMap with concrete class in rxjava library to directly add the properties to Model class and support was mentioned for autoMap with class also in the documentation.
https://github.com/davidmoten/rxjava-jdbc#automap-using-a-concrete-class

But when we were migrating to rxjava2 library, we saw that autoMap feature was removed for concrete class in rxjava2 library and it is present only for interfaces. 
https://github.com/davidmoten/rxjava2-jdbc#automapped-interface-with-default-methods

Also, I saw the code  that column property is mandatory for the fields in the interface and needed function should not have parameters
https://github.com/davidmoten/rxjava2-jdbc/blob/990363055283a491f62c13284dde63326486a748/rxjava2-jdbc/src/main/java/org/davidmoten/rx/jdbc/Util.java#L967

To confirm about Column property, I checked the unit tests and could see that without this annotation we will be throwing an exception.
https://github.com/davidmoten/rxjava2-jdbc/blob/master/rxjava2-jdbc/src/test/java/org/davidmoten/rx/jdbc/DatabaseTest.java#L1269

Could you please elaborate why support was removed for concrete classes in rxjava2 library and Column attribute is made mandatory. 
Also, how can I directly autoMap to model class in rxjava2 library without using a separate interface?
It works if I make a separate interface and then fill the object for model class but I am looking for a way to directly fill the attributes of model class. 
Awaiting your reply.

Thanks,
Shubham

**Comment by davidmoten** [comment]
Hi, concrete class mapping was a bit fiddly (especially when a class has multiple constructors) and I didn't use it much because I preferred having compile-time checking of my use of constructors. What you can do is this:

```java
db
  .select("select name, score from person order by name")
  .get(rs -> new Person(rs.getString("name"), rs.getDouble("score"))
  ...
```

Re the use of Column annotation, this helps I suppose to differentiate from interface methods whose implementation does some calculation using the row values. A simplified example is an interface like:

```java
interface Worth {
    @Column
    double savingsDollars();

    @Column
    double assetsValueDollars();

    default double totalWorthDollars() {
        return savingsDollars() + assetsValueDollars();
    }
}
```

**Comment by shubhamarora97** [comment]
Thanks for the help. This issue is solved now.
