### ISSUE TITLE
Vulnerabilities reported on MVN repo

### ISSUE THREAD

**Issue by umangsingh123** [davidmoten/rxjava2-jdbc#133]
Hi ,
Wanted to check is this still being maintained because i vulnerabilities on MVN and i am afraid on using it .
Thanks 
Umang Singh

**Comment by davidmoten** [comment]
Hi yes it is. What's your concern?

**Comment by davidmoten** [comment]
You mean the log4j deps? They are all test scoped (unit tests only). You choose what logging library you want. I upgrade those deps anyway to remove the vulnerability warnings.

**Comment by davidmoten** [comment]
0.2.11 on Maven Central now with the vulnerability fixes.
