### ISSUE TITLE
Migrate to RxJava3

### ISSUE THREAD

**Issue by brainbytes42** [davidmoten/rxjava2-jdbc#157]
Hi there,

Do you have any plans to migrate to the current Version 3 of RxJava? 

Their [Readme](https://github.com/ReactiveX/RxJava) says: "The [2.x version](https://github.com/ReactiveX/RxJava/tree/2.x) is end-of-life as of **February 28, 2021**. No further development, support, maintenance, PRs and updates will happen."

*Thanks for this library!*

**Comment by davidmoten** [comment]
I don't think the migration is too hard having already migrated rxjava2-pool to rxjava3-pool. I'll put it on my backlog.

**Comment by davidmoten** [comment]
I've migrated. Please check it out: https://github.com/davidmoten/rxjava3-jdbc
