### ISSUE TITLE
returnGeneratedKeys with auto commit enabled

### ISSUE THREAD

**Issue by kdurnoga** [davidmoten/rxjava2-jdbc#20]
When I use the `returnGeneratedKeys` method with auto commit enabled then an error is emitted downstream. Namely, the code of this form
```java
db.update("INSERT INTO table1(col1, col2, col3) VALUES(?, ?, ?)")
	.parameters("param1", "param2", "param3")
	.returnGeneratedKeys()
	.autoMap(MyClass.class)
	.singleOrError();
```
correctly emits an inserted object but the following error is raised on completion:
```
org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled.
```
It looks like a flowable constructed by `returnGeneratedKeys` performs a commit on completion and is oblivious to the fact that the underlying connection has auto commits enabled. Connection pools with auto commit enabled seem to be the default(?). 
Am I doing something wrong?

**Comment by davidmoten** [comment]
blocking or non-blocking connection pool?

**Comment by davidmoten** [comment]
Ok, I've added a check on `getAutoCommit()` value before I call commit or rollback (and a unit test). Let me know if that has you sorted. Deployed to Maven Central as 0.1-RC30.

**Comment by kdurnoga** [comment]
It works! Thank you for the prompt reaction.
