### ISSUE TITLE
Inserting NULL values

### ISSUE THREAD

**Issue by kdurnoga** [davidmoten/rxjava2-jdbc#21]
How should NULL values be inserted into nullable columns?
When I pass a Java `null` via the `parameters` call I get
```
java.lang.NullPointerException: Iterator.next() returned a null value 
```
because a `null` appears in a flowable stream (note that this is a stream of query parameters, not a query result set).
When I wrap a null with `Optional.ofNullable` I get
```
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of java.util.Optional. Use setObject() with an explicit Types value to specify the type to use.
```

**Comment by davidmoten** [comment]
As a workaround for the moment this works:

```java
db.update("update person set date_of_birth = :dob")
  .parameter(Parameter.create("dob", null))
```

I'll review null support soon and see what to add. Thanks for the report!

**Comment by davidmoten** [comment]
New null parameter support  in 0.1-RC31 on Maven Central.

See https://github.com/davidmoten/rxjava2-jdbc#null-parameters for details.

**Comment by kdurnoga** [comment]
It works! Thanks.
