### ISSUE TITLE
Automapping with Kotlin doesn't seem to work at all based on the provided examples

### ISSUE THREAD

**Issue by rlperez** [davidmoten/rxjava2-jdbc#33]
Really digging this thing but not having automapping is creating a tremendous workload. I've tried the various things noted in the examples and none of them provide the desired result. It's always errors about annotations.

**Comment by davidmoten** [comment]
You looked at this [example](https://github.com/davidmoten/rxjava2-jdbc/blob/master/rxjava2-jdbc-kotlin-example/src/test/kotlin/RxJava2JdbcKotlinTest.kt) in Kotlin?

**Comment by davidmoten** [comment]
See #11

**Comment by rlperez** [comment]
Yes sir. I also noticed the testing doesn't seem to work on this machine either. Running a maven install on the checked out project leads to a hung command. But I also have created a sample project that I was hoping would simplify what I am really intending to use this for however it just doesn't work unless I run off the result sets. Which my sample code was developed and ran on two different windows machines running two different JVM versions. One runs latest 8 and the other was using Java 10. 

Here is the mvn install output on my windows 10 java 8 machine...it just hangs so I have to kill it. Javac shows 1.8.0_162. 

https://pastebin.com/UZ2Tn6kF

My sample project is https://github.com/rlperez/rxjava-jdbc-example . In the case of this project things work. But I'm not using automapping. When I try to automap things just explode. I either get error messages questioning whether I annotated fields correctly, regardless of whether I make the data class a data class, or an open data class, or create it as an interface. I've tried tagging on the @Query annotation which didn't get my most basic test to pass either. 

I really want to jam with this as I have a longer running project that I was thinking this is a good start either until it's adopted in a broader scope or at least in that in my real project I'm attempting to use it as an implementation of the reactive crud repository in a spring boot app. I'd love to contribute anywhere I can once I can get this working in Kotlin :(

**Comment by davidmoten** [comment]
Thanks for all the detail, that's great! Can you by chance debug this problem for me because I don't have access to a Windows box with git, java, maven?

**Comment by davidmoten** [comment]
I should add that I use Linux only and it is building fine there.

**Comment by rlperez** [comment]
I'm not entirely sure if it's an environmental issue at this point as the project as checked out only fails some on one box however neither seems to work with automapping. I'll follow up shortly. It may be that I have more than a mapping to a single entity...like I have a OneToOne in there.

**Comment by davidmoten** [comment]
closing due inactivity
