### ISSUE TITLE
mapping with select(Class<?>) in transaction fails

### ISSUE THREAD

**Issue by sorinpepelea** [davidmoten/rxjava2-jdbc#35]
i admire your work so much, is just awesome, but
i discovered a bug :
Reproducing the problem :
`Database.test()
.select(Person.class)
.transacted().valuesOnly()
.map(Person::name)// or .map(m -> m.name())
.blockingForEach(v -> System.out.println(v));`

throws an error : cannot convert java.lang.String  to Person ....
even if IDE doesn't complain about anything ... 
seems like in transaction, the library is maping the first column on the resultset only ... 
i tested with first column of type integer .. and i get the error: cannot convert Integer  to Person ....

fixing is simple :

replace the syntax 
[rs -> Util.mapObject(rs, sb.cls, 1),] 
with syntax 
[Util.autoMap(sb.cls)] 
in method 
[private static <T> Flowable<Tx<T>> createFlowable(SelectAutomappedBuilder<T> sb, Database db)]
from class [org.davidmoten.rx.jdbc.TransactedSelectAutomappedBuilder<T>]

`private static <T> Flowable<Tx<T>> createFlowable(SelectAutomappedBuilder<T> sb, Database db) {
        return Flowable.defer(() -> {
            AtomicReference<Connection> connection = new AtomicReference<Connection>();
            return Select.create(
                sb.selectBuilder.connection.map(c -> Util.toTransactedConnection(connection, c)), //
                sb.selectBuilder.parameterGroupsToFlowable(), //
                sb.selectBuilder.sql, //
                sb.selectBuilder.fetchSize, //
                //rs -> Util.mapObject(rs, sb.cls, 1), //please comment this line to fix the bug
				Util.autoMap(sb.cls),//this is the replacing line for fixing the bug 
                false
            ) //
            .materialize() //
            .flatMap(n -> Tx.toTx(n, connection.get(), db)) //
            .doOnNext(tx -> {
                if (tx.isComplete()) {
                    ((TxImpl<T>) tx).connection().commit();
                }
            });
        });
    }`
also . as enhancement

would you considering adding this method as an option
in 
class [org.davidmoten.rx.jdbc.TransactedSelectAutomappedBuilder<T>]
inner class [TransactedSelectAutomappedBuilderValuesOnly<T>]
`public <R> Flowable<R> get(@Nonnull Function<? super T, ? extends R> function) {
            return createFlowable(b.selectBuilder, db).flatMap(Tx.flattenToValuesOnly()).map(function);
        }`

this way ... i could do this :

`Database.test()
.select(Person.class)
.transacted().valuesOnly()
.get(Person::name)
.blockingForEach(v -> System.out.println(v));`

instead of :

`Database.test()
.select(Person.class)
.transacted().valuesOnly()
.get()
.map(Person::name)// or .map(m -> m.name())
.blockingForEach(v -> System.out.println(v));`

**Comment by davidmoten** [comment]
Thanks, I'll have a look (probably tomorrow)

**Comment by davidmoten** [comment]
Thanks for the report and the suggestions. I've included the fix and the extra method in just released 0.2.0 on Maven Central.

**Comment by sorinpepelea** [comment]
thx for fast response
