### ISSUE TITLE
Automapping enums properties

### ISSUE THREAD

**Issue by ianbondoc** [davidmoten/rxjava2-jdbc#72]
Is there a way for automapping a string to enums on select and enums to string when using as query parameter?

**Comment by ianbondoc** [comment]
Was hoping it can support mapping a number of columns to to a class where some fields are enums, not sure what you mean mapping a column directly to an enum, maybe that's also useful if you're after a single column where the value is represented by a an enum,

the other use case i have is the following where the enum is used as a parameter to a statement:
```
       val status = SomeEnumStatus.PENDING
        db.select("SELECT * FROM some_table t WHERE t.status = :status")
            .parameter("status", status)
            .autoMap(SomeEntity::class.java)
```

**Comment by davidmoten** [comment]
Thanks, glad you find it useful. 

I'd suggest you be quite specific with the parameter and pass `.parameter("status", status.name())` or event better `.parameter("status", status.value())` where `value()` is a custom method that carries the String name for use in db tables.

For automapping to an interface I suggest an approach like below. That way if you rename your enums (assuming that you serialize an enum to its `name()` method) then you won't destroy the coordination with the database:

```java
interface PersonWithEnum {
        @Column
        String name();

        @Column("gender")
        String genderCharacter();
        
        default Gender gender() {
            return Gender.fromCode(genderCharacter());
        }
    }
```
I've added an example to DatabaseTest.java: https://github.com/davidmoten/rxjava2-jdbc/blob/a4355c07f9b40d2ed636c49e407575bf7808f59f/rxjava2-jdbc/src/test/java/org/davidmoten/rx/jdbc/DatabaseTest.java#L3553-L3598

**Comment by ianbondoc** [comment]
thanks that makes sense, i just got used to spring where it provides converters for you, but this is good enough
