### ISSUE TITLE
Caching result with CachedRowSet.populate fails

### ISSUE THREAD

**Issue by ITCMYL** [davidmoten/rxjava2-jdbc#84]
Due to the fact that rxjava2-jdbc prepares statements with a cursor that is FORWARD_ONLY, caching the result set, eg via CachedRowSet.populate, doesn't work (at least with Java 16)

.) either the result set is missing the very first row (because CachedRowSet.populate(rs) executes rs.next(), effectively incrementing the rs a second time) 

...
       .select(query)
       .parameters(queryParams)
       .get(rs -> cachedRowSet.populate(rs))    <---- first row is skipped, becauce of rs.next() inside populate

.) or it fails with an exception when doing CachedRowSet.populate(rs, 1) because the cursor is not movable.

...
       .select(query)
       .parameters(queryParams)
       .get(rs -> cachedRowSet.populate(rs, 1))    <---- Exception because cursor cannot be moved to the beginning

Is there any plan to at least make the ResultType setting for PreparedStatements configurable instead of the hardcoded FORWARD_ONLY? Or do we miss how caching the result set for later processing would work out-of-the box?

**Comment by davidmoten** [comment]
Ok, i haven't used this caching business with jdbc. Would like to make a PR and we can talk further?

**Comment by MaYaITC** [comment]
Not sure if we have time or resources for doing a PR and changes. I was just wondering if the maintainers are aware of this... deficiency, Regardless of the fact if someone really "needs" cached data - the moment the ResultSet is fed into CachedRowSet.populate it either misses a row or throws. Just wanted to report this. We implemented our own workaround by caching the result set manually, using a customized (but inferior) CachedRowSet implementation.
